import { BrandingConfig } from './branding.config';

export const UILabels = {
  // Login Page
  LOGIN: {
    TITLE: 'Iniciar Sessió',
    SUBTITLE: 'Sistema de Menjador Escolar',
    EMAIL_LABEL: 'Correu electrònic',
    EMAIL_PLACEHOLDER: BrandingConfig.EMAIL.PLACEHOLDER,
    PASSWORD_LABEL: 'Contrasenya',
    PASSWORD_PLACEHOLDER: 'La teva contrasenya',
    SUBMIT_BUTTON: 'Iniciar Sessió',
    SUBMIT_BUTTON_LOADING: 'Iniciant sessió...',
    FORGOT_PASSWORD_LINK: 'Has oblidat la contrasenya?',
    REGISTER_LINK: 'No tens un compte?',
    GOOGLE_LOGIN_BUTTON: 'Accedir amb Google',
  },

  // Registration Page
  REGISTRATION: {
    TITLE: "Registre d'Estudiant",
    SUBTITLE: 'Sistema de Menjador Escolar',
    EMAIL_LABEL: 'Correu electrònic',
    EMAIL_PLACEHOLDER: 'el@teu.email',
    NAME_LABEL: 'Nom',
    NAME_PLACEHOLDER: 'El teu nom',
    LAST_NAME_LABEL: 'Cognoms',
    LAST_NAME_PLACEHOLDER: 'Els teus cognoms',
    VERIFICATION_CODE_LABEL: 'Codi de verificació',
    PASSWORD_LABEL: 'Contrasenya',
    PASSWORD_PLACEHOLDER: 'La teva contrasenya',
    PASSWORD_CONFIRMATION_LABEL: 'Confirma la Contrasenya',
    PASSWORD_CONFIRMATION_PLACEHOLDER: 'Introduïu la contrasenya de nou',
    SEND_CODE_BUTTON: 'Enviar codi',
    SEND_CODE_BUTTON_LOADING: 'Enviant...',
    COMPLETE_REGISTRATION_BUTTON: 'Completar registre',
    COMPLETE_REGISTRATION_BUTTON_LOADING: 'Registrant...',
    LOGIN_LINK: 'Ja tens compte? Inicia sessió',
    EMAIL_REQUIRED_ERROR: 'El correu és obligatori.',
    EMAIL_FORMAT_ERROR: 'Format de correu no vàlid.',
    EMAIL_DOMAIN_ERROR: `Només es permeten correus ${BrandingConfig.EMAIL.DOMAIN}.`,
    PASSWORDS_MISMATCH_ERROR: 'Les contrasenyes no coincideixen.',
  },

  // Forgot Password Page
  FORGOT_PASSWORD: {
    TITLE: 'Recuperar contrasenya',
    EMAIL_PLACEHOLDER: 'Introdueix el teu correu',
    NEW_PASSWORD_PLACEHOLDER: 'Nova contrasenya',
    REPEAT_PASSWORD_PLACEHOLDER: 'Repeteix la contrasenya',
  },

  // Common Form Labels
  COMMON: {
    SUBMIT: 'Enviar',
    CANCEL: 'Cancel·lar',
    SAVE: 'Guardar',
    DELETE: 'Eliminar',
    EDIT: 'Editar',
    CLOSE: 'Tancar',
    CONFIRM: 'Confirmar',
    BACK: 'Tornar',
  },

  // History Page
  HISTORY: {
    TITLE: 'Historial de Comandes',
    SUBTITLE: 'Consulta les teves comandes anteriors',
    BACK_TO_MENU: 'Tornar al menú',
    NO_ORDERS: "No tens comandes a l'historial.",
    HAS_TUPPER: 'Ha portat tàper',
    FIRST_DISH: 'Primer Plat',
    SECOND_DISH: 'Segon Plat',
    DESSERT: 'Postre',
  },

  // Navigation Bar
  NAVIGATION: {
    FOOD: 'Menú',
    HISTORY: 'Historial',
    ADMIN: 'Admin',
    PROFILE: 'Perfil',
    DASHBOARD: 'Tauler',
  },

  // Footer
  FOOTER: {
    COPYRIGHT: BrandingConfig.COMPANY.COPYRIGHT,
    AUTHOR: BrandingConfig.COMPANY.AUTHOR,
    PROJECT_NAME: BrandingConfig.APP.NAME,
  },

  // Profile / User Card
  PROFILE: {
    TITLE: 'El meu perfil',
    SUBTITLE: 'Gestiona la teva identitat digital',
    VERIFIED_ACCOUNT: 'Compte verificat',
    STUDENT_DATA: "Dades de l'alumne",
    NAME: 'Nom',
    LAST_NAME: 'Cognoms',
    EMAIL: 'Email del compte',
    ACCESS_CONTROL: "Control d'Accés",
    PASSWORD: 'Contrasenya',
    UPDATE: 'Actualitzar',
    LOGOUT: 'Tancar sessió',
    EXIT: 'Sortir',
    STATUS: 'Estat del compte',
    ACTIVE: 'Actiu',
    PROFILE_PROGRESS: 'Progrés del perfil',
    ENROLLED: 'Inscrit',
    MEAL_SERVICE_ACTIVE: 'Servei de menjador actiu',
    CURRENT_BALANCE: 'Saldo actual',
    ADD_BALANCE: 'Afegir Saldo',
    TWO_FACTOR_TITLE: 'Autenticació en dos passos',
    TWO_FACTOR_ENABLED: 'Activat',
    TWO_FACTOR_DISABLED: 'Desactivat',
    TWO_FACTOR_ENABLE: 'Activar',
    TWO_FACTOR_DISABLE: 'Desactivar',
    TWO_FACTOR_ERROR_GENERATE: "No s'ha pogut generar el secret de 2FA.",
    TWO_FACTOR_SUCCESS_DISABLE:
      "S'ha desactivat l'autenticació en dos passos correctament.",
    TWO_FACTOR_ERROR_DISABLE: "No s'ha pogut desactivar el 2FA.",
    TWO_FACTOR_BUTTON_LABEL: '2FA Autenticació',
    ALLERGIES_TITLE: 'Al·lèrgies i Intoleràncies',
    ALLERGIES_SUBTITLE: "Ajuda'ns a cuidar de la teva salut al menjador",
    DIETARY_CONFIG: 'Configuració alimentària',
    OTHER_OBSERVATIONS: 'Altres observacions o detalls',
    COMMA_SEPARATED: 'Separa-les amb comes',
    CUSTOM_ALLERGIES_PLACEHOLDER:
      'Ex: Pinya, maduixes, intolerància severa al marisc...',
    TWO_FACTOR_SUBTITLE:
      "Escaneja el codi QR amb la teva app d'autenticació (Google Authenticator, Microsoft Authenticator, etc.)",
    TWO_FACTOR_SECRET_LABEL: 'Teu secret (manual):',
    TWO_FACTOR_CODE_LABEL: 'Codi de verificació:',
    TWO_FACTOR_VERIFY: 'Verificar i Activar',
    TWO_FACTOR_CANCEL: 'Cancel·lar',
    TWO_FACTOR_SUCCESS: '2FA Activat correctament',
    TWO_FACTOR_ERROR_VERIFY: 'Codi incorrecte, torna-ho a provar',
    TWO_FACTOR_ERROR: 'Error de verificació en dos passos.',
    SAVE_CHANGES: 'Guardar canvis',
    TABS: {
      PROFILE: 'El meu perfil',
      ALLERGIES: 'Al·lèrgies',
      CONFIG: 'Configuració',
      TRANSACTIONS: 'Transaccions',
    },
    ROLES: {
      ADMIN: 'Administrador',
      USER: 'Alumne',
      COOK: 'Cuina',
    },
  },

  // Welcome Page
  WELCOME: {
    SELECT_MENU: 'Seleccionar Menú',
    PROJECT_NAME: BrandingConfig.APP.NAME,
  },

  // Menu Selection Page
  MENU_SELECTION: {
    TITLE: 'Selecció de Menú',
    SUBTITLE: 'Tria els teus plats preferits per a cada dia',
    TAPER_LABEL: 'Opció de Tàper',
    TAPER_SUBTITLE: 'Portaré el meu propi',
    SELECT_DAY: 'Selecciona el dia',
    MENU_TYPE_TITLE: 'Tipus de menú',
    RESTRICTED_DATE_TITLE: 'Data no disponible',
    EMPTY_STATE:
      'Tria un tipus de menú per començar a configurar la teva reserva',
    DOWNLOAD_BUTTON: 'Descarregar Menú',
    CONFIRM_BUTTON: 'Confirmar Comanda',
    ORDER_EXISTS: 'Ja tens una comanda per aquest dia',
    DEADLINE_PASSED_TODAY: "L'hora límit per demanar per avui ha passat",
    DEADLINE_PASSED_PAST: 'No es poden fer comandes per a dies passats',
    DEADLINE_DAYS_AHEAD: "Cal demanar amb {days} dia/es d'antelació",
    ERROR_BALANCE_UPDATE:
      'Error en actualitzar el saldo. Per favor, torna-ho a intentar.',
    ERROR_IMAGE_DOWNLOAD: 'Error en descarregar la imatge',
    TYPE_PREFIX: 'Tipus',
    WEEK_OF: 'Setmana del',
    DAYS_SHORT: ['Dl', 'Dt', 'Dc', 'Dj', 'Dv'],
    TAPER_YES: 'Portaré Tàper',
    TAPER_NO: 'No portaré Tàper',
    CONFIRM: 'Confirmar',
  },

  // Modals
  MODALS: {
    INTRO: {
      TITLE: 'Benvingut/da al Menjador!',
      DESCRIPTION:
        'Tria el teu menú diari de forma fàcil i ràpida. Recorda revisar les alèrgies per assegurar la teva comanda.',
      BUTTON: 'Començar ara',
    },
    CONFIRM: {
      TITLE: 'Confirmar comanda',
      DATE: 'Data',
      MENU_TYPE: 'Tipus de Menú',
      OPTIONS: 'Opcions triades',
      OWN_TUPPER: 'Amb tàper propi',
      SUBTOTAL: 'Preu menú',
      TUPPER_SURCHARGE: 'Suplement tàper',
      PRICE: 'Preu total',
      BALANCE: 'El teu saldo',
      REMAINING_BALANCE: 'Saldo restant',
      INSUFFICIENT_FUNDS: 'Saldo insuficient',
      RECHARGE: 'RECARREGAR SALDO',
      QUESTION_1: 'Estàs segur/a que vols confirmar aquesta selecció?',
      QUESTION_2:
        'Ara pots tornar enrere per fer canvis però després no podràs modificar res.',
      BACK: 'Tornar enrere',
      CONFIRM: 'SÍ, CONFIRMAR',
    },
  },
  // Transactions Page
  TRANSACTIONS: {
    TITLE: 'Historial de Transaccions',
    ADMIN_TITLE: 'Gestió de Transaccions',
    DATE: 'Data',
    DESCRIPTION: 'Descripció',
    TYPE: 'Tipus',
    AMOUNT: 'Import',
    STATUS: 'Estat',
    NO_TRANSACTIONS: "No s'han trobat transaccions.",
    TYPES: {
      TOPUP: 'Recàrrega',
      ORDER: 'Comanda',
      CORRECTION: 'Correció',
    },
    SEARCH_PLACEHOLDER: 'Cerca per usuari, descripció, estat...',
    SHOWING: 'Mostrant',
    OF: 'de',
    TRANSACTIONS_LC: 'transaccions',
  },
  ADMIN: {
    CONFIG: {
      TITLE: 'Configuració del Sistema',
      SUBTITLE: 'Gestiona la configuració del sistema',
      IMAGES_TAB: 'Imatges Menú',
      SCHEDULES_TAB: 'Horaris',
      PRICES_TAB: 'Preus',
      STATUS_TAB: "Estat de l'App",
      REDSYS_TAB: 'Pagaments',
      CONFIG_TAB: 'Configuració',
      PAGINATION_TAB: 'Paginació',
      IMAGES_TITLE: 'Imatges dels Menús Mensuals',
      IMAGES_DESC:
        'Puja les imatges dels menús perquè els usuaris les puguin consultar.',
      IMG_START_DATE: 'Inici visibilitat',
      IMG_END_DATE: 'Final visibilitat',
      NEW_IMG_START: 'Nova Data Inici',
      NEW_IMG_END: 'Nova Data Fi',
      SAVE_IMAGE: 'Desar',
      UPLOAD_NEW: 'Puja una nova imatge',
      UPLOAD_BUTTON: 'Pujar imatge',
      UPLOADING_BUTTON: 'Pujant...',
      UPLOADING: 'Pujant...',
      ORDERS_TITLE: 'Configuració de Comandes',
      DEADLINE_TIME: 'Hora límit per la comanda',
      DEADLINE_TIME_DESC:
        "Si els dies d'antelació són 0, aquesta hora s'aplica per a comandes del mateix dia. Si és major que 0, l'hora s'ignora ja que prevalen els dies d'antelació.",
      DAYS_AHEAD: "Dies d'antelació",
      DAYS_AHEAD_DESC:
        "Quants dies abans s'ha de tancar la comanda. Si és 0, es pot demanar per al mateix dia fins a l'hora límit.",
      MENU_PRICE: 'Preu Menú Complet (€)',
      MENU_PRICE_DESC: '',
      TAPER_PRICE: 'Preu Tupper (€)',
      TAPER_PRICE_DESC: '',
      HALF_MENU_FIRST_PRICE: 'Preu Mig Menú (1r plat) (€)',
      HALF_MENU_FIRST_PRICE_DESC: '',
      HALF_MENU_SECOND_PRICE: 'Preu Mig Menú (2n plat) (€)',
      HALF_MENU_SECOND_PRICE_DESC: '',
      SAVE_CHANGES: 'Guardar Canvis',
      SAVING: 'Guardant...',
      APP_STATUS_TITLE: "Estat de l'Aplicació",
      APP_STATUS_DESC:
        "Si desactives l'aplicació, els usuaris veuran una pàgina de manteniment.",
      APP_ACTIVE: 'Aplicació Activa',
      APP_ACTIVE_DESC: "L'aplicació està funcionant normalment",
      APP_INACTIVE_DESC: "L'aplicació està en manteniment",
      MAINTENANCE_TITLE: 'Estem en manteniment',
      MAINTENANCE_DESC:
        "Estem realitzant algunes millores al sistema per oferir-te un millor servei. Torna a intentar-ho d'aquí a una estona.",
      REDSYS_TITLE: 'Configuració de la Passarel·la de Redsys',
      REDSYS_DESC: 'Configura les claus i paràmetres de connexió amb Redsys.',
      REDSYS_URL: "URL de l'Entorn (Proves/Real)",
      REDSYS_CODE: 'Codi de Comerç (FUC)',
      REDSYS_TERMINAL: 'Terminal',
      REDSYS_KEY: 'Clau Secreta (SHA-256)',
      MAINTENANCE_FOOTER: 'Gràcies per la teva paciència',
      PAGINATION_TITLE: 'Configuració de Paginació',
      PAGINATION_DESC:
        'Configura el nombre de registres que es mostren per pàgina a cada secció.',
      ORDERS_PER_PAGE: 'Comandes per pàgina',
      USERS_PER_PAGE: 'Usuaris per pàgina',
      TRANSACTIONS_PER_PAGE: 'Transaccions per pàgina',
      IMAGE_DELETE_CONFIRM: 'Estàs segur que vols eliminar aquesta imatge?',
      IMAGE_DELETE_SUCCESS: 'Imatge eliminada correctament',
      IMAGE_DELETE_ERROR: 'Error en eliminar la imatge',
      IMAGE_UPLOAD_SUCCESS: 'Imatge pujada correctament',
      IMAGE_UPLOAD_ERROR: 'Error en pujar la imatge',
      DATES_REQUIRED: 'Les dates són obligatòries',
      DATES_UPDATE_SUCCESS: 'Dates actualitzades correctament',
      DATES_UPDATE_ERROR: 'Error en actualitzar les dates',
      PAYMENT_PROVIDER: 'Proveïdor de Pagaments',
      STRIPE_PUBLIC_KEY: 'Stripe Public Key',
      STRIPE_SECRET_KEY: 'Stripe Secret Key',
      WEBHOOK: 'Webhook',
    },
    DASHBOARD: {
      TITLE: 'Panell de Control',
      TABS: {
        ORDERS: 'ordres',
        MENUS: 'menus',
        USERS: 'usuaris',
        TRANSACTIONS: 'transaccions',
      },
      LABELS: {
        ORDERS: 'Ordres',
        MENUS: 'Menús',
        USERS: 'Usuaris',
        TRANSACTIONS: 'Transaccions',
        LIST_VIEW: 'Llista',
        KANBAN_VIEW: 'Kanban',
        SEARCH_ORDERS_PLACEHOLDER: 'Cerca comandes per nom, email o data...',
        SEARCH_USERS_PLACEHOLDER: 'Cerca usuaris per nom o email...',
        SHOWING: 'Mostrant',
        OF: 'de',
        ORDERS_LC: 'comandes',
        YES: 'Sí',
        NO: 'No',
        PICK_DATE: 'Selecciona una data',
      },
      ORDERS: {
        TITLE: "Gestió d'Ordres",
        EXPORT: 'Exportar',
        PREVIOUS_DAY: 'Dia anterior',
        NEXT_DAY: 'Dia següent',
        TABLE: {
          USER: 'Usuari',
          EMAIL: 'Email',
          DATE: 'Data',
          TYPE: 'Tipus',
          ALLERGIES: 'Al·lèrgies',
          FIRST_DISH: 'Primer plat',
          SECOND_DISH: 'Segon plat',
          DESSERT: 'Postre',
          STATUS: 'Estat',
          TUPPER: 'Tupper',
        },
        NO_ORDERS: "No s'han trobat ordres per a la data seleccionada.",
      },
      MENUS: {
        TITLE: 'Gestió de Menús',
        PREVIOUS_WEEK: 'Setmana anterior',
        NEXT_WEEK: 'Setmana següent',
        IMPORT: 'Importar menús',
        NO_MENUS: 'No hi han menús per a la data seleccionada',
      },
      USERS: {
        TITLE: "Gestió d'Usuaris",
        IMPORT: 'Importar usuaris',
        TABLE: {
          ID: 'ID',
          NAME: 'Nom',
          LAST_NAME: 'Cognoms',
          EMAIL: 'Email',
          ROLE: 'Rol',
          BALANCE: 'Balanç',
          STATUS: 'Estat',
        },
        ACTIVE: 'Actiu',
        INACTIVE: 'Inactiu',
      },
    },
  },
  PAYMENT: {
    TOP_UP: {
      TITLE: 'Afegir Saldo',
      BACK_BUTTON: 'Tornar al perfil',
      DIRECT_MODE_TITLE: 'Suma Directa',
      PACKS_MODE_TITLE: 'Paquets de Menús',
      DIRECT_MODE_DESC: 'Selecciona la quantitat que vols afegir',
      PACKS_MODE_DESC: 'Calcula el total segons els teus menús',
      CUSTOM_AMOUNT_PLACEHOLDER: 'Altre quantitat',
      FULL_MENU_LABEL: 'Menú Complet',
      TAPER_LABEL: 'Suplement Tàper',
      HALF_MENU_FIRST_LABEL: 'Mig Menú (1r plat)',
      HALF_MENU_SECOND_LABEL: 'Mig Menú (2n plat)',
      UNIT: 'unitat',
      TOTAL_LABEL: 'Total a pagar',
      LIMIT_WARNING: 'El límit màxim per transacció és de 150,00€',
      ADD_BALANCE_BUTTON: 'Afegir al saldo',
      PROCESSING: 'Processant...',
    },
  },
};
